export const ERROR_CODES = {
  // Unexpected Error Codes.
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Common Error Codes.
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_CONFLICTED: 'EMAIL_CONFLICTED',

  // Url Service Error Codes.
  URL_NOT_FOUND: 'URL_NOT_FOUND',
  INVALID_URL_SCHEME: 'INVALID_URL_SCHEME',
  INVALID_URL_FORMAT: 'INVALID_URL_FORMAT',
  URL_NOT_ACTIVATED: 'URL_NOT_ACTIVATED',
  URL_EXPIRED: 'URL_EXPIRED',
  ADVANCED_SETTINGS_UNAUTHORIZED: 'ADVANCED_SETTINGS_UNAUTHORIZED',

  // User Service Error Codes.
  INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  RESET_PASSWORD_EXPIRED: 'RESET_PASSWORD_EXPIRED',

  // Email Service Error Codes.
  SEND_EMAIL_FAILED: 'SEND_EMAIL_FAILED',
  INVALID_CODE: 'INVALID_CODE',

  // Captcha Service Error Codes.
  CAPTCHA_VERIFICATION_FAILED: 'CAPTCHA_VERIFICATION_FAILED',

  // Validation Error Codes.
  REQUIRED: 'REQUIRED',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_LENGTH: 'INVALID_LENGTH',
  LENGTH_OVERFLOW: 'LENGTH_OVERFLOW',
};
